#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 100)
    M = random.randint(1, 9)
    # 1~9からM個重複なしでランダムに抽出
    A = random.sample([i for i in range(1, 10)], M)
    print(N, M)
    print(*A)

if __name__ == "__main__":
    main()
