#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 20)  # TODO: edit here
    A = [None for _ in range(N)]
    C = [None for _ in range(N)]
    L = random.randint(1, 20)  # TODO: edit here
    K = random.randint(1, 20)  # TODO: edit here
    K = min(K, L)
    for i in range(N):
        A[i] = random.randint(1, L - 1)  # TODO: edit here
        C[i] = random.randint(1, 20)  # TODO: edit here
    A.sort()
    print(N, L, K)
    for i in range(N):
        print(A[i], C[i])

if __name__ == "__main__":
    main()
