#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(3, 20)
    p = random.sample([i for i in range(N)], N)
    print(N)
    print(*[p[i] for i in range(N)])

if __name__ == "__main__":
    main()
