#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    testcases = random.randint(1, 1)  # TODO: edit here
    N = [None for _ in range(testcases)]
    A = [[] for _ in range(testcases)]
    for i in range(testcases):
        N[i] = random.randint(5, 20)  # TODO: edit here
        for a in range(1, N[i] + 1):
            A[i].append(a)
        for a in range(1, N[i] + 1):
            A[i].append(a)
        random.shuffle(A[i])
    print(testcases)
    for i in range(testcases):
        print(N[i])
        print(*A[i])

if __name__ == "__main__":
    main()
