#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    C = ['.', '#']
    H = random.randint(5, 10)  # TODO: edit here
    W = random.randint(5, 10)  # TODO: edit here
    S = [[None for _ in range(W)] for _ in range(H)]
    for i in range(H):
        for j in range(W):
            S[i][j] = C[random.randint(0, 1)]  # TODO: edit here
    print(H, W)
    for i in range(H):
        print(''.join(S[i]))

if __name__ == "__main__":
    main()
