#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    t = 1
    print(t)
    for _ in range(t):
        N = random.randrange(1, 20)
        A = [random.randrange(1, 30) for _ in range(N)]
        print(N)
        print(*A)

if __name__ == "__main__":
    main()
